spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate
    show-sql: false
  cloud:
    aws:
      region:
        static: ${AWS_REGION}
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      s3:
        bucket: ${AWS_BUCKET_NAME}
      cdn:
        url: ${AWS_CDN_URL}

auth:
  jwt:
    secret-key: ${TOKEN_SECRET}
    refresh-token-expiry: ${REFRESH_TOKEN_EXPIRY}
    access-token-expiry: ${ACCESS_TOKEN_EXPIRY}

oauth:
  apple:
    key-id: ${APPLE_KEY_ID}
    team-id: ${APPLE_TEAM_ID}
    client-id: ${APPLE_CLIENT_ID}
  kakao:
    admin-key: ${KAKAO_ADMIN_KEY}