name: Pull Request Test & CI

on:
  workflow_dispatch:
  pull_request:
    branches:
      - dev

env:
  TF_DIR: infra
  TFVARS: ${{ secrets.TFVARS }}
  JAVA_VER: 17
  JAVA_DIST: corretto

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VER }}

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Test with Gradle
        run: ./gradlew test
        shell: bash
  build-and-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: ${{ env.JAVA_DIST }}
          java-version: ${{ env.JAVA_VER }}
      
      - name: Setup Environment Variables
        run: |
          sudo touch .env
          sudo chmod 755 .env
          echo "${{ secrets.ENV_VARS }}" | sudo tee -a .env
          source .env
        shell: bash

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew clean build -x test
        shell: bash
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/gongmeda/yeobee/app:latest